In [26]:
import pandas as pd

In [9]:
sales = pd.Series([4200, 5100, 8900, 7600] , index=["a" , "b" , "c" , "d"])
sales["a"]

np.int64(4200)

In [19]:
## data frame 

data = {
  "name":["anuj" , "priya" , "anshu"],
  "age":[20 , 18 , 24],
  "marks":[45 , 60 , 90],
  
}

pandas = pd.DataFrame(data , index=["student_1" , "student_2" , "student_3"])
print(pandas)
print("")
print(pandas["age"])
print("")
print(pandas.shape)
print("")
print(pandas.dtypes)
print("")
print(pandas.info())

            name  age  marks
student_1   anuj   20     45
student_2  priya   18     60
student_3  anshu   24     90

student_1    20
student_2    18
student_3    24
Name: age, dtype: int64

(3, 3)

name       str
age      int64
marks    int64
dtype: object

<class 'pandas.DataFrame'>
Index: 3 entries, student_1 to student_3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 96.0+ bytes
None

In [21]:
data = {
  "name":["anuj" , "priya" , "anshu"],
  "age":[20 , 18 , 24],
  "marks":[45 , 60 , 90],
  
}

pandas = pd.DataFrame(data , index=["student_1" , "student_2" , "student_3"])

## convert dataframe to numpy

arr = pandas["age"].to_numpy
print(arr)

<bound method IndexOpsMixin.to_numpy of student_1    20
student_2    18
student_3    24
Name: age, dtype: int64>

In [27]:
df = pd.read_csv("tip.csv")
print(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [30]:
df["size"].describe()

count    244.000000
mean       2.569672
std        0.951100
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        6.000000
Name: size, dtype: float64

In [55]:
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [32]:
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [33]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [34]:
df["day"].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [36]:
df["day"].nunique()

4

In [48]:
df.iloc[-15::][::-1]

     total_bill   tip     sex smoker   day    time  size
243       18.78  3.00  Female     No  Thur  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
239       29.03  5.92    Male     No   Sat  Dinner     3
238       35.83  4.67  Female     No   Sat  Dinner     3
237       32.83  1.17    Male    Yes   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
232       11.61  3.39    Male     No   Sat  Dinner     2
231       15.69  3.00    Male    Yes   Sat  Dinner     3
230       24.01  2.00    Male    Yes   Sat  Dinner     4
229       22.12  2.88  Female    Yes   Sat  Dinner     2

In [53]:
df.iloc[5]

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

In [54]:
df.loc[5]

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

In [62]:
df[(df["tip"] > 5) & (df["size"] > 2)]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [68]:
df.loc[ df["day"]=="Sun" , ["tip" , "time"]]

      tip    time
0    1.01  Dinner
1    1.66  Dinner
2    3.50  Dinner
3    3.31  Dinner
4    3.61  Dinner
..    ...     ...
186  3.50  Dinner
187  2.00  Dinner
188  3.50  Dinner
189  4.00  Dinner
190  1.50  Dinner

[76 rows x 2 columns]

In [69]:
## isnull
df.isnull()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [73]:
df.isnull().sum().sum()

np.int64(0)

In [76]:
df.duplicated().sum()

np.int64(1)

In [77]:
df.groupby("day")["tip"].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [78]:
ti = pd.read_csv("Titanic-Dataset.csv")

In [80]:
ti.shape
print("row" , ti.shape[0])
print("column" , ti.shape[1])

row 891
column 12

In [82]:
ti.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [83]:
ti.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [84]:
ti.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [85]:
ti.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [89]:
ti.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [90]:
ti.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [93]:
## count , min , max  , std , mean , 50% , 25% , 75% 
ti["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [100]:
## shape , info()

print(ti.shape)
print("")
print(ti.info())

print(((891-714)*100/891).__round__(1))

(891, 12)

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
None
19.9

In [101]:
import numpy as np
a = np.arange(12).reshape(3, 4)
b = a[:, 1:3]
b[0, 0] = 999
a[0, 1]

np.int64(999)